Sigsum requires go1.22
sigsum-go requires go1.22 according to go.mod and pkg/requests is indeed unhappy with go1.19.8.
```
go/pkg/mod/sigsum.org/sigsum-go@v0.9.1/pkg/requests/witness.go:95:22: undefined: strings.CutPrefix
```